# Generated by Django 5.2.12 on 2026-03-27 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код кафедры')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное название')),
                ('short_name', models.CharField(max_length=50, verbose_name='Краткое название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('achievements', models.TextField(blank=True, verbose_name='Достижения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Заведующий кафедрой')),
                ('staff', models.ManyToManyField(blank=True, related_name='department_staff', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники кафедры')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
                'ordering': ['short_name'],
            },
        ),
    ]
