# Generated by Django 5.2.14 on 2026-05-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('METHODIST', 'Методист кафедры'), ('NIO_STAFF', 'Сотрудник НИО')], default='NIO_STAFF', max_length=20, verbose_name='Роль'),
        ),
    ]
