# Generated by Django 6.0.3 on 2026-03-18 08:34

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('soft_delete', 'Мягкое удаление'), ('hard_delete', 'Физическое удаление'), ('restore', 'Восстановление'), ('delete_request', 'Запрос на удаление'), ('delete_request_approved', 'Одобрение запроса'), ('delete_request_rejected', 'Отклонение запроса'), ('login', 'Вход в систему'), ('logout', 'Выход из системы')], max_length=30, verbose_name='Действие')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Журнал активности',
                'verbose_name_plural': 'Журнал активности',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeleteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Причина удаления')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Запрос на удаление',
                'verbose_name_plural': 'Запросы на удаление',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название публикации/мероприятия')),
                ('author', models.CharField(max_length=255, verbose_name='Автор(ы)')),
                ('circulation', models.CharField(blank=True, max_length=100, verbose_name='Тираж')),
                ('head', models.CharField(blank=True, max_length=255, verbose_name='Руководитель')),
                ('executors', models.TextField(blank=True, verbose_name='Исполнители')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Место проведения')),
                ('event_name', models.CharField(blank=True, max_length=255, verbose_name='Название мероприятия')),
                ('funding_source', models.CharField(blank=True, max_length=255, verbose_name='Источник финансирования')),
                ('volume', models.CharField(blank=True, max_length=100, verbose_name='Объём')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('students_names', models.TextField(blank=True, verbose_name='ФИО студентов')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(core.models.current_year)], verbose_name='Год издания')),
                ('students_count', models.PositiveIntegerField(default=0, verbose_name='Количество студентов')),
                ('pages_count', models.PositiveIntegerField(default=0, verbose_name='Количество страниц')),
                ('result', models.CharField(blank=True, choices=[('участник', 'Участник'), ('призёр', 'Призёр'), ('победитель', 'Победитель')], max_length=20, verbose_name='Результат')),
                ('department', models.CharField(choices=[('КТОиТК', 'Кафедра таможенных операций и таможенного контроля'), ('КТиТЭ', 'Кафедра товароведения и таможенной экспертизы'), ('КУиЭТД', 'Кафедра управления и экономики таможенного дела'), ('КЭТиМЭО', 'Кафедра экономической теории и международных экономических отношений'), ('КГПД', 'Кафедра государственно-правовых дисциплин'), ('КГрПД', 'Кафедра гражданско-правовых дисциплин'), ('КУПД', 'Кафедра уголовно-правовых дисциплин'), ('КГД', 'Кафедра гуманитарных дисциплин'), ('КИЯ', 'Кафедра иностранных языков'), ('КИиИТТ', 'Кафедра информатики и информационных таможенных технологий'), ('КФП', 'Кафедра физической подготовки')], max_length=100, verbose_name='Кафедра')),
                ('entry_month', models.IntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], default=3, verbose_name='Месяц внесения')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Дата проведения')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('marked_for_deletion', 'Помечена на удаление'), ('archived', 'Архивирована')], default='active', max_length=20, verbose_name='Статус записи')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-created_at'],
            },
        ),
    ]
