# Generated by Django 6.0.3 on 2026-03-18 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='deleterequest',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delete_requests', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель'),
        ),
        migrations.AddField(
            model_name='deleterequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_delete_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кем рассмотрено'),
        ),
        migrations.AddField(
            model_name='publication',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи'),
        ),
        migrations.AddField(
            model_name='deleterequest',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_requests', to='core.publication', verbose_name='Публикация'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='core.publication', verbose_name='Публикация'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['status', '-created_at'], name='core_public_status_bb8ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['department', 'year'], name='core_public_departm_398151_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['title'], name='core_public_title_1c693a_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-timestamp'], name='core_activi_timesta_8baae3_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-timestamp'], name='core_activi_user_id_d7adda_idx'),
        ),
    ]
