# Generated by Django 5.2.12 on 2026-03-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ключевые слова'),
        ),
    ]
