# Generated by Django 5.2.12 on 2026-03-30 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_publication_keywords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.AddField(
            model_name='publication',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_publications', to=settings.AUTH_USER_MODEL, verbose_name='Кем проверено'),
        ),
        migrations.AddField(
            model_name='publication',
            name='moderation_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий модератора'),
        ),
        migrations.AddField(
            model_name='publication',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус модерации'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('soft_delete', 'Мягкое удаление'), ('hard_delete', 'Физическое удаление'), ('restore', 'Восстановление'), ('delete_request', 'Запрос на удаление'), ('delete_request_approved', 'Одобрение запроса'), ('delete_request_rejected', 'Отклонение запроса'), ('moderation_approved', 'Публикация одобрена'), ('moderation_rejected', 'Публикация отклонена'), ('login', 'Вход в систему'), ('logout', 'Выход из системы')], max_length=30, verbose_name='Действие'),
        ),
    ]
