# Generated by Django 5.2.12 on 2026-03-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_publication_moderated_at_publication_moderated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='citation_db',
            field=models.CharField(blank=True, choices=[('РИНЦ', 'РИНЦ'), ('ВАК', 'ВАК'), ('WOS', 'WOS'), ('Scopus', 'Scopus'), ('Другие издания', 'Другие издания'), ('Другие зарубежные издания', 'Другие зарубежные издания')], max_length=50, verbose_name='База данных и система цитирования'),
        ),
    ]
