# Generated by Django 5.2.12 on 2026-04-01 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_publication_citation_db'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название издательства')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='author_status',
            field=models.CharField(blank=True, choices=[('staff', 'Штатный сотрудник'), ('student', 'Студент'), ('compatibility', 'Совместитель'), ('external', 'Внешний сотрудник')], max_length=20, verbose_name='Статус автора'),
        ),
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=100, verbose_name='DOI'),
        ),
        migrations.AddField(
            model_name='publication',
            name='edn_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='EDN'),
        ),
        migrations.AddField(
            model_name='publication',
            name='elibrary_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ELibrary ID'),
        ),
        migrations.AddField(
            model_name='publication',
            name='printed_sheets',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Объём в печатных листах'),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_scope',
            field=models.CharField(blank=True, choices=[('international', 'Международное'), ('all_russian', 'Всероссийское'), ('regional', 'Региональное'), ('interuniversity', 'Межвузовское'), ('internal', 'Внутривузовское')], max_length=20, verbose_name='Уровень публикации'),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(blank=True, choices=[('article', 'Статья'), ('student_article', 'Статья студента'), ('monograph', 'Монография'), ('textbook', 'Учебник'), ('tutorial', 'Учебное пособие'), ('conference_paper', 'Тезисы докладов'), ('software_certificate', 'Свидетельство ЭВМ'), ('patent', 'Патенты на изобретения'), ('student_research', 'НИРС'), ('conference', 'Научная конференция'), ('forum', 'Научный форум'), ('competition', 'Научный конкурс'), ('exhibition', 'Выставка'), ('round_table', 'Круглый стол'), ('conference_collection', 'Сборник трудов конференции')], max_length=30, verbose_name='Тип публикации'),
        ),
        migrations.AddField(
            model_name='publication',
            name='reporting_period',
            field=models.CharField(blank=True, choices=[('1_quarter', '1 квартал'), ('2_quarter', '2 квартал'), ('3_quarter', '3 квартал'), ('4_quarter', '4 квартал'), ('1_period', '1 период'), ('2_period', '2 период'), ('3_period', '3 период'), ('4_period', '4 период'), ('annual', 'Годовой отчёт')], max_length=20, verbose_name='Отчётный период'),
        ),
        migrations.AddField(
            model_name='publication',
            name='reporting_year',
            field=models.CharField(blank=True, max_length=10, verbose_name='Отчётный год'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='circulation',
            field=models.PositiveIntegerField(default=0, verbose_name='Тираж'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='citation_db',
            field=models.CharField(blank=True, choices=[('RINC', 'РИНЦ'), ('VAK', 'ВАК'), ('WOS', 'WOS'), ('SCOPUS', 'Scopus'), ('OTHER_DB', 'Другие издания'), ('NONE', 'Без индексации')], max_length=50, verbose_name='База данных и система цитирования'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='entry_month',
            field=models.IntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], default=4, verbose_name='Месяц внесения'),
        ),
        migrations.AddField(
            model_name='publication',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='core.publisher', verbose_name='Издательство'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['publication_type'], name='core_public_publica_101f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['citation_db'], name='core_public_citatio_c7c1a7_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['reporting_period'], name='core_public_reporti_9131bf_idx'),
        ),
    ]
