# Generated by Django 5.2.12 on 2026-04-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_new_publication_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.TextField(verbose_name='Автор(ы)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.TextField(verbose_name='Название публикации/мероприятия'),
        ),
    ]
