# Generated by Django 5.2.12 on 2026-04-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_increase_title_author_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.TextField(unique=True, verbose_name='Название издательства'),
        ),
    ]
