# Generated by Django 5.2.12 on 2026-04-08 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_increase_title_author_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['is_archived', '-created_at'], name='core_public_is_arch_8c134b_idx'),
        ),
    ]
