# Generated by Django 5.2.13 on 2026-05-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_is_archived_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='entry_month',
            field=models.IntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], default=5, verbose_name='Месяц внесения'),
        ),
    ]
